/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class in_weargenius_gpio_DigitalOutputPin */

#ifndef _Included_in_weargenius_gpio_DigitalOutputPin
#define _Included_in_weargenius_gpio_DigitalOutputPin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_weargenius_gpio_DigitalOutputPin
 * Method:    GPIOWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_in_weargenius_gpio_DigitalOutputPin_GPIOWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     in_weargenius_gpio_DigitalOutputPin
 * Method:    GPIOUnexport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_in_weargenius_gpio_DigitalOutputPin_GPIOUnexport
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
